replicas: 4
name: blogs-service
namespace: app
image: 802564302645.dkr.ecr.ap-southeast-1.amazonaws.com/blog-service
#image: blog-service
#version: error #Stable version
#version: nginx2 #Preview version
#version: nginx3 #Preview version
#version: m1
autoPromotionEnabled: false
scaleDownDelayRevisionLimit: 2
revisionHistoryLimit: 3
container:
  port: 8080
service:
  type: LoadBalancer
  port: 8080
  protocol: TCP
config:
  MONGO_CONNNECTION_URL: "mongodb+srv://adminuser:snODcIVpzX6xPJiX@blogs.nbsxxog.mongodb.net/blogs"
  MONGO_DATABASE_NAME: "blogs"
  MONGO_COLLECTION_NAME: "blogs"



