apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    blueGreen: 
      activeService: {{ .Values.name }}
      previewService: {{ .Values.name }}-preview
      autoPromotionEnabled: false
      abortScaleDownDelaySeconds: 0
      scaleDownDelayRevisionLimit: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}:{{ .Values.version | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.container.port }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blogs-env